### ISSUE TITLE
REVIEW Week 11

### ISSUE THREAD

**Issue by tienyulin** [Hyphasis/floofloo#58]
Please look at PR #57 . Thanks.

**Comment by chinyakao** [comment]
There are some errors in you `rake spec_accept` in these week.
In your github action, it only runs `rake spec`, but you have accept test and spec_all test.
Would you like to add in github action?

**Comment by StevenTimeTW** [comment]
@chinyakao  Thanks Riley.

We just found that error happened unexpectedly yesterday, and we have found the reason. 
We will fix that in our next PR. Thanks for raising that error.

Yes, we will add that in our GitHub action once we fix the bug this week.

Thanks again !
